myclient_django/myclient/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from myclient.forms import MyUniqueEmailRegistrationForm
from registration.backends.hmac.views import RegistrationView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='accounts/login'), name='login'),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=MyUniqueEmailRegistrationForm),
       name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^profile/', include('profiles.urls'))
]

myclient_django/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from profiles.views import IndexView, AddAccountView, AccountDetailView, EmailBodyView, SendEmailView, SettingsView, \
    AddressBookView, AddContactView, ContactView, EditContactView, DeleteContactView
    # , SentView, TrashView

app_name = 'profiles'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # url(r'^add-account$', views.add_account, name='add_account'),
    # url(r'^(?P<email_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<email_id>[0-9]+)/(?P<message_id>[0-9]+)/$', views.email_body, name='email_body'),
    # url(r'^(?P<email_id>[0-9]+)/send/$', views.send_email, name='send_email'),
    # url(r'^settings/$', views.settings, name='settings'),

    url(r'^$', login_required(IndexView.as_view()), name='index'),
    url(r'^add-account$', login_required(AddAccountView.as_view()), name='add_account'),
    url(r'^(?P<account_id>[0-9]+)/(?P<folder_index>[0-9]+)/$', login_required(AccountDetailView.as_view()), name='detail'),
    url(r'^(?P<account_id>[0-9]+)/(?P<folder_index>[0-9]+)/(?P<message_id>[0-9]+)/$', login_required(EmailBodyView.as_view()), name='email_body'),
    url(r'^(?P<account_id>[0-9]+)/send/$', login_required(SendEmailView.as_view()), name='send_email'),
    url(r'^settings/$', login_required(SettingsView.as_view()), name='settings'),
    url(r'^address-book/$', login_required(AddressBookView.as_view()), name='address_book'),
    url(r'^address-book/(?P<contact_id>[0-9]+)/$', login_required(ContactView.as_view()), name='contact_details'),
    url(r'^address-book/add-contact/$', login_required(AddContactView.as_view()), name='add_contact'),
    url(r'^address-book/edit/(?P<contact_id>[0-9]+)/$', login_required(EditContactView.as_view()), name='edit_contact'),
    url(r'^address-book/delete/(?P<contact_id>[0-9]+)/$', login_required(DeleteContactView.as_view()), name='delete_contact'),
]

myclient_django/profiles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class UserEmails(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=32)
    imap = models.CharField(max_length=100)
    smtp = models.CharField(max_length=100)

    def __str__(self):
        return self.email


class AddressBook(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=32)
    other_info = models.TextField(max_length=2000)

    def __str__(self):
        return self. name

myclient_django/profiles/forms.py
from django import forms
from .models import UserEmails, AddressBook
from .utils import validate_input


class AddEmailForm(forms.Form):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    imap = forms.CharField(max_length=100)
    smtp = forms.CharField(max_length=100)

    def add_email(self, user_id):
        self.email = self.cleaned_data['email']
        self.password = self.cleaned_data['password']
        self.imap = self.cleaned_data['imap']
        self.smtp = self.cleaned_data['smtp']
        error = validate_input(self.email, self.password, self.imap, self.smtp)
        if error:
            return error
        else:
            row = UserEmails(user_id=user_id, email=self.email, password=self.password, imap=self.imap, smtp=self.smtp)
            row.save()


class SendEmailForm(forms.Form):
    to = forms.CharField(required=True)
    subject = forms.CharField(max_length=100)
    message = forms.Field(widget=forms.Textarea)


class AddContactForm(forms.ModelForm):
    class Meta:
        model = AddressBook
        fields = ['name', 'surname', 'email', 'phone', 'other_info']

myclient_django/profiles/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic.edit import FormView, UpdateView, DeleteView, CreateView

from .forms import AddEmailForm, SendEmailForm, AddContactForm
from .utils import get_mailbox, get_email_body, send, delete_mails, get_folders
from .models import UserEmails, AddressBook
from . import utf

import re


class AccountDetailView(View):
    def post(self, request, account_id, folder_index):
        boxes = request.POST.getlist('boxes')
        account_row = UserEmails.objects.filter(id=account_id)
        password = account_row.values('password').get()['password']
        username = account_row.values('email').get()['email']
        imap = account_row.values('imap').get()['imap']
        folders, names = get_folders(username, password, imap)

        clicked = folders[int(folder_index)]
        to_select = names[clicked]
        headers = get_mailbox(username, password, imap, to_select)

        if 'delete' in request.POST:
            folders, names = get_folders(username, password, imap)
            clicked = folders[int(folder_index)]
            to_select = names[clicked]
            delete_mails(imap, username, password, boxes, to_select)
            headers = get_mailbox(username, password, imap, to_select)
        return render(request, 'profiles/detail.html',
                      {'headers': headers, 'account_id': account_id, 'username': username, 'folder': clicked,
                       'folders': folders})

    def get(self, request, account_id, folder_index):
        account_row = UserEmails.objects.filter(id=account_id)
        password = account_row.values('password').get()['password']
        username = account_row.values('email').get()['email']
        imap = account_row.values('imap').get()['imap']
        folders, names = get_folders(username, password, imap)
        clicked = folders[int(folder_index)]
        print(clicked)
        to_select = names[clicked]
        headers = get_mailbox(username, password, imap, to_select)
        return render(request, 'profiles/detail.html',
                      {'headers': headers, 'account_id': account_id, 'username': username, 'folder': clicked,
                       'folders': folders, 'folder_index': folder_index})


class SendEmailView(View):
    def post(self, request, account_id):
        form = SendEmailForm(request.POST, request.FILES)
        if form.is_valid():
            account_row = UserEmails.objects.filter(id=account_id)
            password = account_row.values('password').get()['password']
            username = account_row.values('email').get()['email']
            smtp = account_row.values('smtp').get()['smtp']
            to = form.cleaned_data['to'].split(',')
            for email in to:
                if not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email):
                    error = "Not a valid email address!"
                    return render(request, 'profiles/send_email.html', {'form': form, 'error': error})
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            print("To: ", to, "Mess: ", message, "Subj: ", subject)
            files = [f for f in request.FILES.getlist('datafile')]
            result = send(smtp, username, password, to, subject, message, files)
            form = SendEmailForm()  # 4tob o4istiti posle otpravki
            if not result:
                success = 'Message successfully sent!'
                return render(request, 'profiles/send_email.html', {'form': form, 'success': success})
            return render(request, 'profiles/send_email.html', {'form': form, 'error': result})
        return render(request, 'profiles/send_email.html', {'form': form})

    def get(self, request, account_id):
        form = SendEmailForm()
        return render(request, 'profiles/send_email.html', {'form': form})


class ContactView(View):
    def get(self, request, contact_id):
        selected_contact = AddressBook.objects.get(id=contact_id)
        return render(request, 'profiles/contact_details.html',
                      {'contact': selected_contact})


class AddContactView(CreateView):
    template_name = 'profiles/add_contact.html'
    form_class = AddContactForm
    success_url = '/profile/address-book/'
    model = AddressBook

    def form_valid(self, form):
        contact = form.save(commit=False)
        contact.user_id = self.request.user.id
        contact.save()
        return redirect(self.success_url)


class EditContactView(UpdateView):
    template_name = 'profiles/contact_edit.html'
    form_class = AddContactForm
    success_url = '/profile/address-book/'
    model = AddressBook

    def get_object(self, queryset=None):
        obj = AddressBook.objects.get(id=self.kwargs['contact_id'])
        return obj


class DeleteContactView(DeleteView):
    form_class = AddContactForm
    success_url = '/profile/address-book/'
    model = AddressBook

    def get_object(self, queryset=None):
        obj = AddressBook.objects.get(id=self.kwargs['contact_id'])
        return obj


class AddressBookView(View):
    def get(self, request):
        contacts = AddressBook.objects.filter(user_id=request.user.id)
        return render(request, 'profiles/address_book.html', {'contacts': contacts})

    def post(self, request):
        contacts = AddressBook.objects.filter(user_id=request.user.id)
        return render(request, 'profiles/address_book.html', {'contacts': contacts})


class AddAccountView(FormView):
    template_name = 'profiles/add_account.html'
    form_class = AddEmailForm
    success_url = '/profile/'

    def form_valid(self, form):
        error = form.add_email(self.request.user.id)
        if error:
            return render(self.request, self.template_name, {'form': form, 'error': error})
        return redirect(self.success_url)

    def form_invalid(self, form):
        return super(AddAccountView, self).form_invalid(form)


class SettingsView(View):
    def post(self, request):
        accounts = UserEmails.objects.filter(user_id=request.user.id)
        boxes = request.POST.getlist('boxes')
        for box in boxes:
            to_delete = accounts[int(box)]
            try:
                UserEmails.objects.filter(user_id=request.user.id).filter(email=to_delete).delete()
            except Exception as ex:
                print(ex)
        accounts = UserEmails.objects.filter(user_id=request.user.id)
        return render(request, 'profiles/settings.html', {'accounts': accounts})

    def get(self, request):
        accounts = UserEmails.objects.filter(user_id=request.user.id)
        return render(request, 'profiles/settings.html', {'accounts': accounts})


class EmailBodyView(View):
    def get(self, request, account_id, message_id, folder_index):
        try:
            account_row = UserEmails.objects.filter(id=account_id)
            password = account_row.values('password').get()['password']
            username = account_row.values('email').get()['email']
            imap = account_row.values('imap').get()['imap']
            folders, names = get_folders(username, password, imap)
            clicked = folders[int(folder_index)]
            print(clicked)
            to_select = names[clicked]
            # print(username, password, imap)
            email_text = get_email_body(username, password, imap, message_id, to_select)
        except Exception as ex:
            print(ex)
            return redirect('/profile')
        return render(request, 'profiles/email_body.html', {'email_body': email_text})


class IndexView(View):
    def get(self, request):
        accounts = UserEmails.objects.filter(user_id=request.user.id)
        return render(request, 'profiles/main.html', {'accounts': accounts})


        # In this, and others below i should've used login_required decorator.

        # def index(request):
        # username = request.user.get_username()
        # accounts = UserEmails.objects.filter(user_id=request.user.id)
        # return render(request, 'profiles/main.html', {'username': username, 'accounts': accounts})

        # def add_account(request):
        #     if request.method == 'POST':
        #         username = request.user.get_username()
        #         user_id = request.user.id
        #         form = AddEmailForm(request.POST)
        #         if form.is_valid():
        #             email = form.cleaned_data['email']
        #             password = form.cleaned_data['password']
        #             imap = form.cleaned_data['imap']
        #             smtp = form.cleaned_data['smtp']
        #             error = validate_input(email, password, imap, smtp)
        #             if error:
        #                 print(error)
        #                 return render(request, 'profiles/add_account.html', {'form': form, 'error': error})
        #             row = UserEmails(user_id=user_id, email=email, password=password, imap=imap, smtp=smtp)
        #             row.save()
        #             return redirect('/profile/')
        #     else:
        #         form = AddEmailForm()
        #     return render(request, 'profiles/add_account.html', {'form': form})

        # def detail(request, email_id):
        #     accounts = UserEmails.objects.filter(user_id=request.user.id)
        #     email = accounts[int(email_id)]
        #     account_row = UserEmails.objects.filter(email=email)
        #     password = account_row.values('password').get()['password']
        #     username = account_row.values('email').get()['email']
        #     imap = account_row.values('imap').get()['imap']
        #     if request.method == 'POST':
        #         boxes = request.POST.getlist('boxes')
        #         delete_mails(imap, username, password, boxes)
        #         headers = get_mailbox(username, password, imap)

myclient_django/profiles/templates/profiles/add_account.html
{% extends "profiles/base.html" %}
{% block content %}
    {% load staticfiles %}
    {% load widget_tweaks %}

    <form action="{% url 'profiles:add_account' %}" method="post" autocomplete="off">
        {% csrf_token %}
        <div class="login-form" style="margin: 10% 20% 10%; width:400pt;">
            <h4 style="margin: 0 0 5% 30%;">Add an account</h4>
            <div class="form-group">
                {% render_field form.email type="email" class="form-control login-field" value="" placeholder="Enter your email" id="account-email" %}
                <label class="login-field-icon fui-mail" for="account-email"></label>
            </div>

            <div class="form-group">
                {% render_field form.password type="password" class="form-control login-field" value="" placeholder="Enter your password" id="account-email" %}
                <label class="login-field-icon fui-lock" for="account-email"></label>
            </div>
            <div class="form-group">
                {% render_field form.imap type="text" class="form-control login-field" value="" placeholder="Enter IMAP server" id="account-imap" %}
            </div>
            <div class="form-group">
                {% render_field form.smtp type="text" class="form-control login-field" value="" placeholder="Enter SMTP server" id="account-smtp" %}
            </div>
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit"/>
            <div class="text-danger">
                {% if error %}
                    <ul>
                    <li style="margin: 3%"><p>{{ error }}</p></li>
                    </ul>
                {% endif %}
                {% for field in form %}
                    <p>{{ field.errors }}</p>
                {% endfor %}
            </div>
        </div>
    </form>
{% endblock %}

myclient_django/profiles/templates/profiles/add_contact.html
{% extends "profiles/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
    <h4>Add a contact:</h4>
    <form class="form-horizontal" action="{% url 'profiles:add_contact' %}" method="post" autocomplete="off"
          role="form">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="row">
                    <label for="{{ field.label }}" class="col-lg-2 control-label">{{ field.label }}</label>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        {% render_field field type="text" rows="5" class="form-control" id=field.label %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <p><input style="width: 230pt" class="btn btn-primary btn-lg" type="submit" value="Add"/></p>
                    <div class="text-danger">
                        {% for field in form %}
                            <p>{{ field.errors }}</p>
                        {% endfor %}
                    </div>
                </div>

            </div>

        </div>

    </form>
{% endblock %}

myclient_django/profiles/templates/profiles/address_book.html
{% extends "profiles/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
    <h4>Your contacts:</h4>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Phone</th>
        </tr>
        </thead>
        <tbody>
        {% for contact in contacts %}
            <tr onclick="window.document.location='{% url 'profiles:contact_details' contact.id %}';">
                <td>
                    {{ contact.name }}
                </td>
                <td>
                   {{ contact.surname }}
                </td>
                <td>
                    {{ contact.email }}
                </td>
                <td>
                    {{ contact.phone }}
                </td>

            </tr>

        {% endfor %}
        </tbody>
    </table>
    <p><a style="width:150pt" class="btn btn-md btn-primary" type="submit"
          href="{% url 'profiles:add_contact' %}">Add a contact</a></p>

{% endblock %}

myclient_django/profiles/templates/profiles/addressbook_confirm_delete.html
{% extends "profiles/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
    <form action="." method="post" autocomplete="off">
        {% csrf_token %}
        <div class="col-lg-2 col-md-3 col-sm-3"></div>
        <h4>Are you sure you want to delete {{ object.name }} {{ object.surname }}?</h4>
        <div class="col-lg-3 col-md-3 col-sm-3"></div>
        <div style="margin: 5% 0 0 0" class="col-lg-4 col-md-4 col-sm-4"><input style="width:100pt" class="btn btn-md btn-danger" type="submit" value="Yes"/></div>
         <div style="margin: 5% 0 0 0" class="col-lg-4 col-md-4 col-sm-4"><a style="width:100pt" class="btn btn-md btn-primary" type="submit"
                                                                              href="javascript:history.back()">No</a></div>
    </form>
{% endblock %}
style="margin: 0% 0 5% 25%;"

myclient_django/profiles/templates/profiles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Mail App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    {% load staticfiles %}

    <!-- Loading Bootstrap -->
    <link href="{% static 'dist/css/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="{% static 'dist/css/flat-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'docs/assets/css/demo.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

</head>
<body>
<header>
    <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-6">
                <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="{% url 'profiles:index' %}">Home</a>
            <a class="navbar-brand" href="{% url 'profiles:address_book' %}">Address Book</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-6">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'profiles:settings' %}"><span class="visible-sm visible-xs">Settings<span
                        class="fui-gear"></span></span><span
                        class="visible-md visible-lg"><span class="fui-gear"></span></span></a></li>
                <li><a href="/accounts/logout/"><span class="visible-sm visible-xs">Log out<span
                        class="fui-exit"></span></span><span
                        class="visible-md visible-lg"><span class="fui-exit"></span></span></a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</header>
{% block detail %}
{% endblock %}
<div class="container" >
    {% block content %}
    {% endblock %}
</div>

<!-- /.container -->

<!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
<script src="{% static 'dist/js/vendor/jquery.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'docs/assets/js/application.js' %}"></script>
<script src="{% static 'dist/js/flat-ui.min.js' %}"></script>

</body>
</html>

myclient_django/profiles/templates/profiles/contact_details.html
{% extends "profiles/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
    <h4>{{ contact.name }} {{ contact.surname }}</h4>
    <p><span style="color: #3498db">Email: </span>{{ contact.email }}</p>
    <p><span style="color: #3498db">Phone: </span>{{ contact.phone }}</p>
    <p><span style="color: #3498db">Info: </span>{{ contact.other_info }}</p>
    <p><a style="width:150pt" class="btn btn-md btn-primary" type="submit"
          href="{% url 'profiles:edit_contact' contact.id %}">Edit</a></p>
    <p><a style="width:150pt" class="btn btn-md btn-danger" type="submit"
          href="{% url 'profiles:delete_contact' contact.id %}">Delete</a></p>
{% endblock %}

myclient_django/profiles/templates/profiles/contact_edit.html
{% extends "profiles/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
    <h4>Contact edit:</h4>
    <form class="form-horizontal" action="." method="post" autocomplete="off">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="row">
                    <label for="{{ field.label }}" class="col-lg-2 control-label">{{ field.label }}</label>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        {% render_field field type="text" rows="5" class="form-control" id=field.label %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <p><input style="width: 230pt" class="btn btn-primary btn-lg" type="submit" value="Edit"/></p>
                    <div class="text-danger">
                        {% for field in form %}
                            <p>{{ field.errors }}</p>
                        {% endfor %}
                    </div>
                </div>

            </div>

        </div>
    </form>
{% endblock %}

myclient_django/profiles/templates/profiles/detail.html
{% extends "profiles/base.html" %}
{% block detail %}
    <script language="JavaScript">
        function toggle(source) {
            checkboxes = document.getElementsByName('boxes');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script>

    <div class="col-lg-2 col-md-2 col-sm-2" style="margin: 5.4% 2% 0 3%;padding-left: 0;padding-right: 0;width: 100pt;">
        {#        <form action="." method="post" autocomplete="off">#}
        {#            {% csrf_token %}#}
        {#            {% for f in folders %}#}
        {#                <p><input type="submit" class="btn btn-info btn-sm" value="{{ f }}" name="{{ forloop.counter0 }}" style="width: 90pt;"></p>#}
        {#            {% endfor %}#}
        {#        </form>#}
        {% for f in folders %}
            <p><a href="{% url 'profiles:detail' account_id forloop.counter0 %}" class="btn btn-info btn-sm "
                  style="width: 90pt;"
                  id="{{ f }}">{{ f }}</a></p>
        {% endfor %}
    </div>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <h4>{{ username }}</h4>
        <form action="." method="post" autocomplete="off">
            {% csrf_token %}
            <table class="table table-hover text-nowrap" width="100%">
                <thead>
                <tr>
                    <th style="border: 0" width="5%">
                        <label class="checkbox">
                            <input data-toggle="checkbox" type="checkbox" id="all_checkboxes"
                                   onClick="toggle(this)"/>
                        </label>
                    </th>
                    <th style="border: 0" width="10%">
                        <a class="btn btn-primary btn-sm" style="margin-right: 3%"
                           href="{% url 'profiles:send_email' account_id %}" role="button">Write a
                            message</a>
                        <a href="." class="btn btn-primary btn-sm" style="width: 70pt; margin-right: 3%">Refresh</a>
                    </th>
                    <th style="border: 0"></th>
                    <th style="border: 0; float:right">
                        <input type="submit" class="btn btn-danger btn-sm" style="width: 70pt;" name="delete"
                               value="Delete">
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for h in headers %}
                    <tr>
                        <td>
                            <div class="form-group">
                                <label style="margin: auto" class="checkbox" for="checkbox{{ forloop.counter0 }}">
                                    <input type="checkbox" data-toggle="checkbox" value="{{ forloop.counter0 }}"
                                           id="checkbox{{ forloop.counter0 }}" name="boxes"></label>
                            </div>
                        </td>
                        <td style="font-size: 11pt;"
                            onclick="window.document.location='{% url 'profiles:email_body' account_id folder_index forloop.counter0  %}';">
                            {{ h.0 }}
                        </td>
                        <td style="font-size: 11pt;"
                            onclick="window.document.location='{% url 'profiles:email_body' account_id folder_index forloop.counter0  %}';">
                            {{ h.1 }}. . .
                        </td>
                        <td style="font-size: 11pt;"
                            onclick="window.document.location='{% url 'profiles:email_body' account_id folder_index forloop.counter0  %}';"
                            width="10%">
                            {{ h.2 }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
    <script language="JavaScript">
        var el_id = "{{ folder }}";
        document.getElementById(el_id).className = "btn btn-block btn-sm btn-inverse"
    </script>
{% endblock %}

myclient_django/profiles/templates/profiles/email_body.html
{% extends "base.html" %}
{% block content %}
    {{ email_body }}
{% endblock %}

myclient_django/profiles/templates/profiles/main.html
{% extends "profiles/base.html" %}
{% block content %}
    <div class="login-form" style="margin: 10% 20% 10%; width:400pt;">
        <h4 style="margin: 0 0 5% 26%;">Choose an account</h4>
        <div style="margin: 0 0 0 13%; width:280pt "class="btn-group-vertical">
            {% for account in accounts %}
                <a style="border-radius: 0;" class="btn btn-primary btn-lg btn-embossed" type="button"
                   href="{% url 'profiles:detail' account.id 0 %}">{{ account.email }}</a>
            {% endfor %}
            <p><a style="margin: 34%;" class="login-field" type="button"
                  href="{% url 'profiles:add_account' %}">Add an account</a></p>
        </div>
    </div>
{% endblock %}

myclient_django/profiles/templates/profiles/settings.html
{% extends "profiles/base.html" %}

{% block content %}
    <h4 style="margin: 0 0 3% 1%">Your accounts are:</h4>
    <div class="col-md-9">
        <form action="." method="post" autocomplete="off">
            {% csrf_token %}
            {% for account in accounts %}
                <div class="form-group">
                    <label class="checkbox" for="checkbox{{ forloop.counter0 }}">
                        <input type="checkbox" data-toggle="checkbox" value="{{ forloop.counter0 }}"
                               id="checkbox{{ forloop.counter0 }}" name="boxes">
                        {{ account.email }}
                    </label>
                </div>
            {% endfor %}
            <p><input style="width:150pt" class="btn btn-md btn-danger" type="submit" value="Delete"/></p>
        </form>
    </div>
    <a style="width:150pt; margin: 0 0 2% 0" class="btn btn-md btn-primary" href="{% url 'auth_password_change' %}"
       role="button">Change profile password</a>
    <a style="width:150pt; margin: 0 0 2% 0" class="btn btn-md btn-danger" href="#"
       role="button">Delete profile</a>
{% endblock %}